/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerDetailDataLinksValue
 */
export interface AnswerDetailDataLinksValue {
    /**
     * 
     * @type {string}
     * @memberof AnswerDetailDataLinksValue
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetailDataLinksValue
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetailDataLinksValue
     */
    title?: string;
}

/**
 * Check if a given object implements the AnswerDetailDataLinksValue interface.
 */
export function instanceOfAnswerDetailDataLinksValue(value: object): value is AnswerDetailDataLinksValue {
    return true;
}

export function AnswerDetailDataLinksValueFromJSON(json: any): AnswerDetailDataLinksValue {
    return AnswerDetailDataLinksValueFromJSONTyped(json, false);
}

export function AnswerDetailDataLinksValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDetailDataLinksValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AnswerDetailDataLinksValueToJSON(value?: AnswerDetailDataLinksValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url': value['url'],
        'title': value['title'],
    };
}

