/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerDetailData } from './AnswerDetailData';
import {
    AnswerDetailDataFromJSON,
    AnswerDetailDataFromJSONTyped,
    AnswerDetailDataToJSON,
} from './AnswerDetailData';

/**
 * 
 * @export
 * @interface AnswerDetail
 */
export interface AnswerDetail {
    /**
     * Status.
     * @type {string}
     * @memberof AnswerDetail
     */
    status?: string;
    /**
     * 
     * @type {AnswerDetailData}
     * @memberof AnswerDetail
     */
    data?: AnswerDetailData;
}

/**
 * Check if a given object implements the AnswerDetail interface.
 */
export function instanceOfAnswerDetail(value: object): value is AnswerDetail {
    return true;
}

export function AnswerDetailFromJSON(json: any): AnswerDetail {
    return AnswerDetailFromJSONTyped(json, false);
}

export function AnswerDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : AnswerDetailDataFromJSON(json['data']),
    };
}

export function AnswerDetailToJSON(value?: AnswerDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': AnswerDetailDataToJSON(value['data']),
    };
}

