/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerDetailDataLabeledLinksValue
 */
export interface AnswerDetailDataLabeledLinksValue {
    /**
     * 
     * @type {string}
     * @memberof AnswerDetailDataLabeledLinksValue
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetailDataLabeledLinksValue
     */
    label?: string;
}

/**
 * Check if a given object implements the AnswerDetailDataLabeledLinksValue interface.
 */
export function instanceOfAnswerDetailDataLabeledLinksValue(value: object): value is AnswerDetailDataLabeledLinksValue {
    return true;
}

export function AnswerDetailDataLabeledLinksValueFromJSON(json: any): AnswerDetailDataLabeledLinksValue {
    return AnswerDetailDataLabeledLinksValueFromJSONTyped(json, false);
}

export function AnswerDetailDataLabeledLinksValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDetailDataLabeledLinksValue {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function AnswerDetailDataLabeledLinksValueToJSON(value?: AnswerDetailDataLabeledLinksValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'label': value['label'],
    };
}

