/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchStatusData
 */
export interface BatchStatusData {
    /**
     * The name of a group of documents.
     * @type {string}
     * @memberof BatchStatusData
     */
    domain?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchStatusData
     */
    processedIds?: Array<string>;
}

/**
 * Check if a given object implements the BatchStatusData interface.
 */
export function instanceOfBatchStatusData(value: object): value is BatchStatusData {
    return true;
}

export function BatchStatusDataFromJSON(json: any): BatchStatusData {
    return BatchStatusDataFromJSONTyped(json, false);
}

export function BatchStatusDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchStatusData {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'processedIds': json['processed_ids'] == null ? undefined : json['processed_ids'],
    };
}

export function BatchStatusDataToJSON(value?: BatchStatusData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'domain': value['domain'],
        'processed_ids': value['processedIds'],
    };
}

