/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChunksDetailDataInner
 */
export interface ChunksDetailDataInner {
    /**
     * 
     * @type {string}
     * @memberof ChunksDetailDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChunksDetailDataInner
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ChunksDetailDataInner
     */
    text?: string;
}

/**
 * Check if a given object implements the ChunksDetailDataInner interface.
 */
export function instanceOfChunksDetailDataInner(value: object): value is ChunksDetailDataInner {
    return true;
}

export function ChunksDetailDataInnerFromJSON(json: any): ChunksDetailDataInner {
    return ChunksDetailDataInnerFromJSONTyped(json, false);
}

export function ChunksDetailDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunksDetailDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function ChunksDetailDataInnerToJSON(value?: ChunksDetailDataInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url': value['url'],
        'text': value['text'],
    };
}

