/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatedBatchStatusData } from './CreatedBatchStatusData';
import {
    CreatedBatchStatusDataFromJSON,
    CreatedBatchStatusDataFromJSONTyped,
    CreatedBatchStatusDataToJSON,
} from './CreatedBatchStatusData';

/**
 * 
 * @export
 * @interface CreatedBatchStatus
 */
export interface CreatedBatchStatus {
    /**
     * Status of the batch (e.g., "uploaded", "backlog", "in_progress", "done").
     * @type {string}
     * @memberof CreatedBatchStatus
     */
    status: string;
    /**
     * 
     * @type {CreatedBatchStatusData}
     * @memberof CreatedBatchStatus
     */
    data: CreatedBatchStatusData;
}

/**
 * Check if a given object implements the CreatedBatchStatus interface.
 */
export function instanceOfCreatedBatchStatus(value: object): value is CreatedBatchStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreatedBatchStatusFromJSON(json: any): CreatedBatchStatus {
    return CreatedBatchStatusFromJSONTyped(json, false);
}

export function CreatedBatchStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedBatchStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': CreatedBatchStatusDataFromJSON(json['data']),
    };
}

export function CreatedBatchStatusToJSON(value?: CreatedBatchStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': CreatedBatchStatusDataToJSON(value['data']),
    };
}

