/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentNotFound
 */
export interface DocumentNotFound {
    /**
     * Status.
     * @type {string}
     * @memberof DocumentNotFound
     */
    status: string;
}

/**
 * Check if a given object implements the DocumentNotFound interface.
 */
export function instanceOfDocumentNotFound(value: object): value is DocumentNotFound {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DocumentNotFoundFromJSON(json: any): DocumentNotFound {
    return DocumentNotFoundFromJSONTyped(json, false);
}

export function DocumentNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentNotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function DocumentNotFoundToJSON(value?: DocumentNotFound | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

