/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentDetailDataPagesInner
 */
export interface DocumentDetailDataPagesInner {
    /**
     * The content of the chunk.
     * @type {string}
     * @memberof DocumentDetailDataPagesInner
     */
    text: string;
    /**
     * Two-character language code (e.g., 'en').
     * @type {string}
     * @memberof DocumentDetailDataPagesInner
     */
    language: string;
    /**
     * Optional keywords for search optimization.
     * @type {string}
     * @memberof DocumentDetailDataPagesInner
     */
    keywords?: string;
}

/**
 * Check if a given object implements the DocumentDetailDataPagesInner interface.
 */
export function instanceOfDocumentDetailDataPagesInner(value: object): value is DocumentDetailDataPagesInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function DocumentDetailDataPagesInnerFromJSON(json: any): DocumentDetailDataPagesInner {
    return DocumentDetailDataPagesInnerFromJSONTyped(json, false);
}

export function DocumentDetailDataPagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentDetailDataPagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'language': json['language'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function DocumentDetailDataPagesInnerToJSON(value?: DocumentDetailDataPagesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'text': value['text'],
        'language': value['language'],
        'keywords': value['keywords'],
    };
}

