/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentPagesInner
 */
export interface DocumentPagesInner {
    /**
     * The content of the chunk.
     * @type {string}
     * @memberof DocumentPagesInner
     */
    text: string;
    /**
     * Two-character language code (e.g., 'en').
     * @type {string}
     * @memberof DocumentPagesInner
     */
    language: string;
}

/**
 * Check if a given object implements the DocumentPagesInner interface.
 */
export function instanceOfDocumentPagesInner(value: object): value is DocumentPagesInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function DocumentPagesInnerFromJSON(json: any): DocumentPagesInner {
    return DocumentPagesInnerFromJSONTyped(json, false);
}

export function DocumentPagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentPagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'language': json['language'],
    };
}

export function DocumentPagesInnerToJSON(value?: DocumentPagesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'text': value['text'],
        'language': value['language'],
    };
}

