/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentDetailData } from './DocumentDetailData';
import {
    DocumentDetailDataFromJSON,
    DocumentDetailDataFromJSONTyped,
    DocumentDetailDataToJSON,
} from './DocumentDetailData';

/**
 * 
 * @export
 * @interface DocumentDetail
 */
export interface DocumentDetail {
    /**
     * Status.
     * @type {string}
     * @memberof DocumentDetail
     */
    status: string;
    /**
     * 
     * @type {DocumentDetailData}
     * @memberof DocumentDetail
     */
    data: DocumentDetailData;
}

/**
 * Check if a given object implements the DocumentDetail interface.
 */
export function instanceOfDocumentDetail(value: object): value is DocumentDetail {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DocumentDetailFromJSON(json: any): DocumentDetail {
    return DocumentDetailFromJSONTyped(json, false);
}

export function DocumentDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': DocumentDetailDataFromJSON(json['data']),
    };
}

export function DocumentDetailToJSON(value?: DocumentDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': DocumentDetailDataToJSON(value['data']),
    };
}

