/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainDetailData } from './DomainDetailData';
import {
    DomainDetailDataFromJSON,
    DomainDetailDataFromJSONTyped,
    DomainDetailDataToJSON,
} from './DomainDetailData';

/**
 * 
 * @export
 * @interface DomainDetail
 */
export interface DomainDetail {
    /**
     * Status.
     * @type {string}
     * @memberof DomainDetail
     */
    status: string;
    /**
     * 
     * @type {DomainDetailData}
     * @memberof DomainDetail
     */
    data: DomainDetailData;
}

/**
 * Check if a given object implements the DomainDetail interface.
 */
export function instanceOfDomainDetail(value: object): value is DomainDetail {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DomainDetailFromJSON(json: any): DomainDetail {
    return DomainDetailFromJSONTyped(json, false);
}

export function DomainDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': DomainDetailDataFromJSON(json['data']),
    };
}

export function DomainDetailToJSON(value?: DomainDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': DomainDetailDataToJSON(value['data']),
    };
}

