/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationFailedStatus
 */
export interface OperationFailedStatus {
    /**
     * Status.
     * @type {string}
     * @memberof OperationFailedStatus
     */
    status: string;
}

/**
 * Check if a given object implements the OperationFailedStatus interface.
 */
export function instanceOfOperationFailedStatus(value: object): value is OperationFailedStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OperationFailedStatusFromJSON(json: any): OperationFailedStatus {
    return OperationFailedStatusFromJSONTyped(json, false);
}

export function OperationFailedStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationFailedStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function OperationFailedStatusToJSON(value?: OperationFailedStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

