/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetrieveAnswerRequestUserInfo } from './RetrieveAnswerRequestUserInfo';
import {
    RetrieveAnswerRequestUserInfoFromJSON,
    RetrieveAnswerRequestUserInfoFromJSONTyped,
    RetrieveAnswerRequestUserInfoToJSON,
} from './RetrieveAnswerRequestUserInfo';

/**
 * 
 * @export
 * @interface RetrieveAnswerRequest
 */
export interface RetrieveAnswerRequest {
    /**
     * Natural language query to retrieve or answer.
     * @type {string}
     * @memberof RetrieveAnswerRequest
     */
    question?: string;
    /**
     * 
     * @type {RetrieveAnswerRequestUserInfo}
     * @memberof RetrieveAnswerRequest
     */
    userInfo?: RetrieveAnswerRequestUserInfo;
}

/**
 * Check if a given object implements the RetrieveAnswerRequest interface.
 */
export function instanceOfRetrieveAnswerRequest(value: object): value is RetrieveAnswerRequest {
    return true;
}

export function RetrieveAnswerRequestFromJSON(json: any): RetrieveAnswerRequest {
    return RetrieveAnswerRequestFromJSONTyped(json, false);
}

export function RetrieveAnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveAnswerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'] == null ? undefined : json['question'],
        'userInfo': json['user_info'] == null ? undefined : RetrieveAnswerRequestUserInfoFromJSON(json['user_info']),
    };
}

export function RetrieveAnswerRequestToJSON(value?: RetrieveAnswerRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'question': value['question'],
        'user_info': RetrieveAnswerRequestUserInfoToJSON(value['userInfo']),
    };
}

