/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional user info to track requests.
 * @export
 * @interface RetrieveRequestUserInfo
 */
export interface RetrieveRequestUserInfo {
    /**
     * Unique user ID.
     * @type {string}
     * @memberof RetrieveRequestUserInfo
     */
    id?: string;
}

/**
 * Check if a given object implements the RetrieveRequestUserInfo interface.
 */
export function instanceOfRetrieveRequestUserInfo(value: object): value is RetrieveRequestUserInfo {
    return true;
}

export function RetrieveRequestUserInfoFromJSON(json: any): RetrieveRequestUserInfo {
    return RetrieveRequestUserInfoFromJSONTyped(json, false);
}

export function RetrieveRequestUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveRequestUserInfo {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RetrieveRequestUserInfoToJSON(value?: RetrieveRequestUserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
    };
}
