/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional user info to track requests.
 * @export
 * @interface RetrieveAnswerRequestUserInfo
 */
export interface RetrieveAnswerRequestUserInfo {
    /**
     * Unique user ID.
     * @type {string}
     * @memberof RetrieveAnswerRequestUserInfo
     */
    id?: string;
}

/**
 * Check if a given object implements the RetrieveAnswerRequestUserInfo interface.
 */
export function instanceOfRetrieveAnswerRequestUserInfo(value: object): value is RetrieveAnswerRequestUserInfo {
    return true;
}

export function RetrieveAnswerRequestUserInfoFromJSON(json: any): RetrieveAnswerRequestUserInfo {
    return RetrieveAnswerRequestUserInfoFromJSONTyped(json, false);
}

export function RetrieveAnswerRequestUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveAnswerRequestUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RetrieveAnswerRequestUserInfoToJSON(value?: RetrieveAnswerRequestUserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

