/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional user info to track requests.
 * @export
 * @interface RetrieveRelevanceWeights
 */
export interface RetrieveRelevanceWeights {
    /**
     * The ranking weight for the full-text search factor.
     * @type {number}
     * @memberof RetrieveRelevanceWeights
     */
    text: number;
    /**
     * The ranking weight for the semantic search factor.
     * @type {number}
     * @memberof RetrieveRelevanceWeights
     */
    semantic: number;
}

/**
 * Check if a given object implements the RetrieveRelevanceWeights interface.
 */
export function instanceOfRetrieveRelevanceWeights(value: object): value is RetrieveRelevanceWeights {
    return true;
}

export function RetrieveRelevanceWeightsFromJSON(json: any): RetrieveRelevanceWeights {
    return RetrieveRelevanceWeightsFromJSONTyped(json, false);
}

export function RetrieveRelevanceWeightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveRelevanceWeights {
    if (json == null) {
        return json;
    }
    return {

        'text': json['text'] == null ? undefined : json['text'],
        'semantic': json['semantic'] == null ? undefined : json['semantic'],
    };
}

export function RetrieveRelevanceWeightsToJSON(value?: RetrieveRelevanceWeights | null): any {
    if (value == null) {
        return value;
    }
    return {

        'text': value['text'],
        'semantic': value['semantic'],
    };
}
