/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Telegram /ask command.
 * @export
 * @interface SetupTelegramRequestCommandsAsk
 */
export interface SetupTelegramRequestCommandsAsk {
    /**
     * Menu label.
     * @type {string}
     * @memberof SetupTelegramRequestCommandsAsk
     */
    name?: string;
    /**
     * Message details.
     * @type {string}
     * @memberof SetupTelegramRequestCommandsAsk
     */
    message?: string;
}

/**
 * Check if a given object implements the SetupTelegramRequestCommandsAsk interface.
 */
export function instanceOfSetupTelegramRequestCommandsAsk(value: object): value is SetupTelegramRequestCommandsAsk {
    return true;
}

export function SetupTelegramRequestCommandsAskFromJSON(json: any): SetupTelegramRequestCommandsAsk {
    return SetupTelegramRequestCommandsAskFromJSONTyped(json, false);
}

export function SetupTelegramRequestCommandsAskFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupTelegramRequestCommandsAsk {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SetupTelegramRequestCommandsAskToJSON(value?: SetupTelegramRequestCommandsAsk | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'message': value['message'],
    };
}

