/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetupTelegramRequestCommandsStart } from './SetupTelegramRequestCommandsStart';
import {
    SetupTelegramRequestCommandsStartFromJSON,
    SetupTelegramRequestCommandsStartFromJSONTyped,
    SetupTelegramRequestCommandsStartToJSON,
} from './SetupTelegramRequestCommandsStart';
import type { SetupTelegramRequestCommandsAsk } from './SetupTelegramRequestCommandsAsk';
import {
    SetupTelegramRequestCommandsAskFromJSON,
    SetupTelegramRequestCommandsAskFromJSONTyped,
    SetupTelegramRequestCommandsAskToJSON,
} from './SetupTelegramRequestCommandsAsk';

/**
 * Telegram bot commands.
 * @export
 * @interface SetupTelegramRequestCommands
 */
export interface SetupTelegramRequestCommands {
    /**
     * 
     * @type {SetupTelegramRequestCommandsStart}
     * @memberof SetupTelegramRequestCommands
     */
    start?: SetupTelegramRequestCommandsStart;
    /**
     * 
     * @type {SetupTelegramRequestCommandsAsk}
     * @memberof SetupTelegramRequestCommands
     */
    ask?: SetupTelegramRequestCommandsAsk;
}

/**
 * Check if a given object implements the SetupTelegramRequestCommands interface.
 */
export function instanceOfSetupTelegramRequestCommands(value: object): value is SetupTelegramRequestCommands {
    return true;
}

export function SetupTelegramRequestCommandsFromJSON(json: any): SetupTelegramRequestCommands {
    return SetupTelegramRequestCommandsFromJSONTyped(json, false);
}

export function SetupTelegramRequestCommandsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupTelegramRequestCommands {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : SetupTelegramRequestCommandsStartFromJSON(json['start']),
        'ask': json['ask'] == null ? undefined : SetupTelegramRequestCommandsAskFromJSON(json['ask']),
    };
}

export function SetupTelegramRequestCommandsToJSON(value?: SetupTelegramRequestCommands | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': SetupTelegramRequestCommandsStartToJSON(value['start']),
        'ask': SetupTelegramRequestCommandsAskToJSON(value['ask']),
    };
}

