/* tslint:disable */
/* eslint-disable */
/**
 * QuePasa RAG SaaS API
 * API for RAG retrieval, managing documents, files, and related operations including Telegram integration.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelegramStatus
 */
export interface TelegramStatus {
    /**
     * Status of the operation.
     * @type {string}
     * @memberof TelegramStatus
     */
    status: string;
}

/**
 * Check if a given object implements the TelegramStatus interface.
 */
export function instanceOfTelegramStatus(value: object): value is TelegramStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TelegramStatusFromJSON(json: any): TelegramStatus {
    return TelegramStatusFromJSONTyped(json, false);
}

export function TelegramStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelegramStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function TelegramStatusToJSON(value?: TelegramStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

